-- Name: tec_ecoreference; Type: TABLE;
--

CREATE TABLE public.tec_ecoreference (
    ec_ecid integer NOT NULL,
    ec_eco_code character varying(8) NOT NULL,
    ec_opening_name text NOT NULL
);

ALTER TABLE public.tec_ecoreference ALTER COLUMN ec_ecid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tec_ecoreference_ec_ecid_seq
    START WITH 3999
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tec_ecoreference
    ADD CONSTRAINT tec_ecoreference_ec_eco_code_ec_opening_name_key UNIQUE (ec_eco_code, ec_opening_name);

ALTER TABLE ONLY public.tec_ecoreference
    ADD CONSTRAINT tec_ecoreference_pkey PRIMARY KEY (ec_ecid);

CREATE INDEX idx_tec_code ON public.tec_ecoreference USING btree (ec_eco_code);

--
-- Name: tgd_gamesdecon; Type: TABLE;
-- Canonical source: nextjs-shared/src/chess/schema.sql — keep this block in sync with it.
--

CREATE TABLE public.tgd_gamesdecon (
    gd_gdid integer NOT NULL,
    gd_grid integer NOT NULL,
    gd_white_username character varying(64) NOT NULL,
    gd_black_username character varying(64) NOT NULL,
    gd_white_rating integer NOT NULL,
    gd_black_rating integer NOT NULL,
    gd_player_username character varying(64) NOT NULL,
    gd_player_color character varying(5) NOT NULL,
    gd_player_result character varying(8) NOT NULL,
    gd_opponent_username character varying(64) NOT NULL,
    gd_opponent_rating integer NOT NULL,
    gd_time_class character varying(16) NOT NULL,
    gd_time_control character varying(32),
    gd_is_rated boolean DEFAULT true NOT NULL,
    gd_termination character varying(64),
    gd_end_time integer NOT NULL,
    gd_eco_code character varying(8),
    gd_opening_name text,
    gd_game_url text,
    gd_opening_moves text,
    gd_pgn text,
    gd_chesscom_uuid character varying(64)
);

ALTER TABLE public.tgd_gamesdecon ALTER COLUMN gd_gdid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgd_gamesdecon_gd_gdid_seq
    START WITH 73628
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgd_gamesdecon
    ADD CONSTRAINT tgd_gamesdecon_pkey PRIMARY KEY (gd_gdid);

CREATE INDEX idx_tgd_eco ON public.tgd_gamesdecon USING btree (gd_eco_code);

CREATE INDEX idx_tgd_end_time ON public.tgd_gamesdecon USING btree (gd_end_time DESC);

CREATE UNIQUE INDEX idx_tgd_grid ON public.tgd_gamesdecon USING btree (gd_grid);

CREATE INDEX idx_tgd_opponent ON public.tgd_gamesdecon USING btree (gd_opponent_username);

CREATE INDEX idx_tgd_player ON public.tgd_gamesdecon USING btree (gd_player_username);

CREATE INDEX idx_tgd_result ON public.tgd_gamesdecon USING btree (gd_player_result);

CREATE INDEX idx_tgd_time_class ON public.tgd_gamesdecon USING btree (gd_time_class);

--
-- Name: tgev_game_evals; Type: TABLE;
--

CREATE TABLE public.tgev_game_evals (
    gev_gevid integer NOT NULL,
    gev_game_ref character varying(64) NOT NULL,
    gev_player character varying(64) NOT NULL,
    gev_move_num smallint NOT NULL,
    gev_san text NOT NULL,
    gev_fen_before text NOT NULL,
    gev_fen_after text NOT NULL,
    gev_cp integer,
    gev_cp_before integer,
    gev_cp_loss integer,
    gev_best_move text,
    gev_best_move_san text,
    gev_best_line jsonb,
    gev_classification character varying(12),
    gev_depth smallint
);

ALTER TABLE public.tgev_game_evals ALTER COLUMN gev_gevid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgev_game_evals_gev_gevid_seq
    START WITH 1027
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgev_game_evals
    ADD CONSTRAINT tgev_game_evals_gev_game_ref_gev_player_gev_move_num_key UNIQUE (gev_game_ref, gev_player, gev_move_num);

ALTER TABLE ONLY public.tgev_game_evals
    ADD CONSTRAINT tgev_game_evals_pkey PRIMARY KEY (gev_gevid);

CREATE INDEX idx_tgev_game ON public.tgev_game_evals USING btree (gev_game_ref);

CREATE INDEX idx_tgev_player ON public.tgev_game_evals USING btree (gev_player);

--
-- Name: tgr_gamesraw; Type: TABLE;
-- Canonical source: nextjs-shared/src/chess/schema.sql — keep this block in sync with it.
--

CREATE TABLE public.tgr_gamesraw (
    gr_grid integer NOT NULL,
    gr_player_username character varying(64) NOT NULL,
    gr_chesscom_uuid character varying(64) NOT NULL,
    gr_raw_data jsonb NOT NULL,
    gr_end_time integer NOT NULL,
    gr_time_class character varying(16),
    gr_pgn text
);

ALTER TABLE public.tgr_gamesraw ALTER COLUMN gr_grid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tgr_gamesraw_gr_grid_seq
    START WITH 111342
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tgr_gamesraw
    ADD CONSTRAINT tgr_gamesraw_gr_chesscom_uuid_player_key UNIQUE (gr_chesscom_uuid, gr_player_username);

ALTER TABLE ONLY public.tgr_gamesraw
    ADD CONSTRAINT tgr_gamesraw_pkey PRIMARY KEY (gr_grid);

CREATE INDEX idx_tgr_end_time ON public.tgr_gamesraw USING btree (gr_end_time DESC);

CREATE INDEX idx_tgr_has_pgn ON public.tgr_gamesraw USING btree (gr_grid) WHERE (gr_pgn IS NOT NULL);

CREATE INDEX idx_tgr_player ON public.tgr_gamesraw USING btree (gr_player_username);

--
-- Name: tpl_players; Type: TABLE;
--

CREATE TABLE public.tpl_players (
    pl_plid integer NOT NULL,
    pl_username character varying(64) NOT NULL,
    pl_avatar text,
    pl_display_name character varying(128),
    pl_rating_blitz integer
);

ALTER TABLE public.tpl_players ALTER COLUMN pl_plid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tpl_players_pl_plid_seq
    START WITH 3
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tpl_players
    ADD CONSTRAINT tpl_players_pkey PRIMARY KEY (pl_plid);

ALTER TABLE ONLY public.tpl_players
    ADD CONSTRAINT tpl_players_pl_username_key UNIQUE (pl_username);

--
-- Name: tplr_player_ratings; Type: TABLE;
--

CREATE TABLE public.tplr_player_ratings (
    plr_plrid integer NOT NULL,
    plr_username character varying(64) NOT NULL,
    plr_time_class character varying(16) NOT NULL,
    plr_rating integer NOT NULL
);

ALTER TABLE public.tplr_player_ratings ALTER COLUMN plr_plrid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tplr_player_ratings_plr_plrid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tplr_player_ratings
    ADD CONSTRAINT tplr_player_ratings_pkey PRIMARY KEY (plr_plrid);

ALTER TABLE ONLY public.tplr_player_ratings
    ADD CONSTRAINT tplr_username_timeclass UNIQUE (plr_username, plr_time_class);

CREATE INDEX idx_tplr_username ON public.tplr_player_ratings USING btree (plr_username);

--
-- Name: tsa_savedanalyses; Type: TABLE;
--

CREATE TABLE public.tsa_savedanalyses (
    sa_said integer NOT NULL,
    sa_grid integer,
    sa_save_type character varying(16) NOT NULL,
    sa_title character varying(256),
    sa_notes text,
    sa_line_pgn text,
    sa_line_moves jsonb,
    sa_starting_fen text,
    sa_starting_ply integer,
    sa_tree_data jsonb,
    sa_eco_code character varying(8),
    sa_opening_name text
);

ALTER TABLE public.tsa_savedanalyses ALTER COLUMN sa_said ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tsa_savedanalyses_sa_said_seq
    START WITH 2
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.tsa_savedanalyses
    ADD CONSTRAINT tsa_savedanalyses_pkey PRIMARY KEY (sa_said);

CREATE INDEX idx_tsa_game ON public.tsa_savedanalyses USING btree (sa_grid);

--
-- Name: xlg_logging; Type: TABLE;
--

CREATE TABLE public.xlg_logging (
    lg_lgid integer NOT NULL,
    lg_severity character(1),
    lg_caller character varying DEFAULT ''::character varying,
    lg_functionname character varying NOT NULL,
    lg_msg character varying NOT NULL,
    lg_datetime timestamp with time zone NOT NULL
);

ALTER TABLE public.xlg_logging ALTER COLUMN lg_lgid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xlg_logging_lg_lgid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.xlg_logging
    ADD CONSTRAINT xlg_logging_pkey PRIMARY KEY (lg_lgid);
